let UIView_es = "";
UIView_es += "<!-- toolbar start -->";
UIView_es += "<div class=\"container\">";
UIView_es += "        <nav class=\"navbar navbar-fixed-top navbar-default\" role=\"navigation\">";
UIView_es += "            <div class=\"container-fluid\">";
UIView_es += "                <!-- Collect the nav links, forms, and other content for toggling -->";
UIView_es += "                <div class=\"collapse navbar-collapse\" id=\"bs-navbar-collapse\">";
UIView_es += "                    <ul class=\"nav navbar-nav navbar-right\">";
UIView_es += "                        <li>";
UIView_es += "                            <a href=\"#\" class=\"toolbar pan\" id=\"panBtn\">";
UIView_es += "                                <span class=\"glyphicon glyphicon-toolbar-pan\"><\/span>&nbsp;pan";
UIView_es += "                            <\/a>";
UIView_es += "                        <\/li>";
UIView_es += "                        <li>";
UIView_es += "                            <a href=\"#\" class=\"toolbar fullScreen\" id=\"fullScreenBtn\">";
UIView_es += "                                <span class=\"glyphicon glyphicon-toolbar-fullScreen\"><\/span>&nbsp;fullScreen<\/a>";
UIView_es += "                        <\/li>";
UIView_es += "                        <li>";
UIView_es += "                            <a href=\"#\" class=\"toolbar extent\" id=\"extentBtn\">";
UIView_es += "                                <span class=\"glyphicon glyphicon-toolbar-extent\"><\/span>&nbsp;boxSelected<\/a>";
UIView_es += "                        <\/li>";
UIView_es += "                        <li class=\"dropdown\">";
UIView_es += "                            <a href=\"#\" class=\"dropdown-toggle toolbar measure\" data-toggle=\"dropdown\" id=\"measureBtn\">";
UIView_es += "                                <span class=\"glyphicon glyphicon-toolbar-measure\"><\/span>&nbsp; tools";
UIView_es += "                                <b class=\"caret\"><\/b>";
UIView_es += "                            <\/a>";
UIView_es += "                            <ul class=\"dropdown-menu\">";
UIView_es += "                                <li>";
UIView_es += "                                    <a href=\"#\" class=\"toolbar distance\" id=\"distanceBtn\">";
UIView_es += "                                        <span class=\"glyphicon glyphicon-toolbar-distance\"><\/span>&nbsp; distanceMeasure";
UIView_es += "                                    <\/a>";
UIView_es += "                                <\/li>";
UIView_es += "                                <li>";
UIView_es += "                                    <a href=\"#\" class=\"toolbar area\" id=\"areaBtn\">";
UIView_es += "                                        <span class=\"glyphicon glyphicon-toolbar-area\"><\/span>&nbsp; areMeasure";
UIView_es += "                                    <\/a>";
UIView_es += "                                <\/li>";
UIView_es += "                            <\/ul>";
UIView_es += "                        <\/li>";
UIView_es += "                    <\/ul>";
UIView_es += "                <\/div>";
UIView_es += "                <!-- \/.navbar-collapse -->";
UIView_es += "            <\/div>";
UIView_es += "            <!-- \/.container-fluid -->";
UIView_es += "        <\/nav>";
UIView_es += "    <\/div>";
UIView_es += "<!-- toolbar end -->";

export default UIView_es;