let UIView_zh = "";
UIView_zh += "<!-- 工具栏 start -->";
UIView_zh += "<div class=\"container\">";
UIView_zh += "        <nav class=\"navbar navbar-fixed-top navbar-default\" role=\"navigation\">";
UIView_zh += "            <div class=\"container-fluid\">";
UIView_zh += "                <!-- Collect the nav links, forms, and other content for toggling -->";
UIView_zh += "                <div class=\"collapse navbar-collapse\" id=\"bs-navbar-collapse\">";
UIView_zh += "                    <ul class=\"nav navbar-nav navbar-right\">";
UIView_zh += "                        <li>";
UIView_zh += "                            <a href=\"#\" class=\"toolbar pan\" id=\"panBtn\">";
UIView_zh += "                                <span class=\"glyphicon glyphicon-toolbar-pan\"><\/span>&nbsp;漫游";
UIView_zh += "                            <\/a>";
UIView_zh += "                        <\/li>";
UIView_zh += "                        <li>";
UIView_zh += "                            <a href=\"#\" class=\"toolbar zoomIn\" id=\"zoomInBtn\">";
UIView_zh += "                                <span class=\"glyphicon glyphicon-toolbar-zoomIn\"><\/span>&nbsp;放大";
UIView_zh += "                            <\/a>";
UIView_zh += "                        <\/li>";
UIView_zh += "                        <li>";
UIView_zh += "                            <a href=\"#\" class=\"toolbar zoomOut\" id=\"zoomOutBtn\">";
UIView_zh += "                                <span class=\"glyphicon glyphicon-toolbar-zoomOut\"><\/span>&nbsp;缩小<\/a>";
UIView_zh += "                        <\/li>";
UIView_zh += "                        <li>";
UIView_zh += "                            <a href=\"#\" class=\"toolbar fullScreen\" id=\"fullScreenBtn\">";
UIView_zh += "                                <span class=\"glyphicon glyphicon-toolbar-fullScreen\"><\/span>&nbsp;全图<\/a>";
UIView_zh += "                        <\/li>";
UIView_zh += "                        <li>";
UIView_zh += "                            <a href=\"#\" class=\"toolbar extent\" id=\"extentBtn\">";
UIView_zh += "                                <span class=\"glyphicon glyphicon-toolbar-extent\"><\/span>&nbsp;拉框选择<\/a>";
UIView_zh += "                        <\/li>";
UIView_zh += "                        <li class=\"dropdown\">";
UIView_zh += "                            <a href=\"#\" class=\"dropdown-toggle toolbar measure\" data-toggle=\"dropdown\" id=\"measureBtn\">";
UIView_zh += "                                <span class=\"glyphicon glyphicon-toolbar-measure\"><\/span>&nbsp; 工具";
UIView_zh += "                                <b class=\"caret\"><\/b>";
UIView_zh += "                            <\/a>";
UIView_zh += "                            <ul class=\"dropdown-menu\">";
UIView_zh += "                                <li>";
UIView_zh += "                                    <a href=\"#\" class=\"toolbar distance\" id=\"distanceBtn\">";
UIView_zh += "                                        <span class=\"glyphicon glyphicon-toolbar-distance\"><\/span>&nbsp; 距离测量";
UIView_zh += "                                    <\/a>";
UIView_zh += "                                <\/li>";
UIView_zh += "                                <li>";
UIView_zh += "                                    <a href=\"#\" class=\"toolbar area\" id=\"areaBtn\">";
UIView_zh += "                                        <span class=\"glyphicon glyphicon-toolbar-area\"><\/span>&nbsp; 面积测量";
UIView_zh += "                                    <\/a>";
UIView_zh += "                                <\/li>";
UIView_zh += "                                <li>";
UIView_zh += "                                    <a href=\"#\" class=\"toolbar area\" id=\"printBtn\">";
UIView_zh += "                                        <span class=\"glyphicon glyphicon-toolbar-area\"><\/span>&nbsp; 打印";
UIView_zh += "                                    <\/a>";
UIView_zh += "                                <\/li>";
UIView_zh += "                            <\/ul>";
UIView_zh += "                        <\/li>";
UIView_zh += "                    <\/ul>";
UIView_zh += "                <\/div>";
UIView_zh += "                <!-- \/.navbar-collapse -->";
UIView_zh += "            <\/div>";
UIView_zh += "            <!-- \/.container-fluid -->";
UIView_zh += "        <\/nav>";
UIView_zh += "    <\/div>";
UIView_zh += "<!-- 工具栏 end -->";

export default UIView_zh;